apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  index.html: |
    <html>
    <body>
      <h1>"Домашнее задание к занятию «Конфигурация приложений» - Задание 2 - Мурчин Артем"</h1>
    </body>
    </html>